### ISSUE TITLE
finish dashboard

### ISSUE THREAD

**Issue by Pebin** [tiltom/PV247-Expense-manager#64]

**Comment by SlavoKrupa** [comment]
Display "No data available" for user without data.

**Comment by Lajcisvk** [comment]
On Overview:
there should be category's icons rather than name The name should be hidden in the tooltip
I don't mind if a transaction is repeatable or not – it's overview I would rather see what wallet it is in
Currency does not need stand-alone column, it should be part of the amount
Amount should be right-aligned
