### ISSUE TITLE
Use resource strings and constants

### ISSUE THREAD

**Issue by PetrSvirak** [tiltom/PV247-Expense-manager#74]
* For constants (string and numeric and what ever-else), always create named constant (`…Top(5)` → `const int TopMostItems = 5; …Top(TopMostItems)`)
* For user-facing strings (text messages, …) always use resource files
* It is OK to have only single language, but it is not OK to have localizable strings directly in classes

**Comment by tiltom** [comment]
Put your resource files to the project ExpenseManager.Resources and add them to folders (look at BudgetResources). In case you have some common resource (i.e. delete dialog), put it to SharedResource. Naming conventions will be updated.

One more important thing - set Access Modifier of resources to Public (default is Internal), otherwise you will not be able to see them in ExpenseManager.Web project.

<img width="960" alt="resources access modifier" src="https://cloud.githubusercontent.com/assets/14878713/11564451/97edcadc-99d9-11e5-84e4-210005dfc004.png">

**Comment by redwik** [comment]
Folders with Views done by me:
Account, Budget, BudgetAccessRight, Category, Manage, Shared, Wallet, WalletAccessRight

**Comment by tiltom** [comment]
Make sure all of your models, controllers, views and services are using resources and constants. Also add resource string for successfull edit, create and delete.
