### ISSUE TITLE
When transaction is edited and currency is changed, value is not recalculated

### ISSUE THREAD

**Issue by strho** [tiltom/PV247-Expense-manager#85]

**Comment by Lajcisvk** [comment]
Some weird problem when debugging line by line it recalculates the value, but without debuging it does not work

**Comment by PetrSvirak** [comment]
It will almost surely be an synchronization issue cause by complier optimizations.

First check all usages of all methods like TransactionService.FillTransaction – you are passing an object in (entity), then amend it and return it. However, in code that uses the methods, you simply throw results away expecting the object being passed into the method to prevail its changes (as it is state-full object), rather than consuming method's result.

If this does not help, confirm my premise about optimizations (fast way might consist of logging each method's entrance and exit into a console or a file with a time-stamp and thread ID, better way might be reading this MS article and using VS to aid you: https://msdn.microsoft.com/en-us/library/ms164746.aspx – you can use multiple debug windows (available Debug → Windows, but only when VS is in debug mode) in combination with ``Debugger.Break`` and attaching to a running process)).
