### ISSUE TITLE
All validation messages in forms appears duplicately

### ISSUE THREAD

**Issue by Lajcisvk** [tiltom/PV247-Expense-manager#86]

**Comment by tiltom** [comment]
The reason is we don't load javascript files for jquery validation in the head, but after body is loaded. That causes server catch them and display it as server errors.

There are 2 sollutions:
1. load these files in the head
2. add @section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
} to create and edit views (look at Views/Wallet/Edit)

Solution no. 2 should be better due to performance, so apply it and it will be ok.
