### ISSUE TITLE
Budget sharing with email

### ISSUE THREAD

**Issue by Lajcisvk** [tiltom/PV247-Expense-manager#92]

**Comment by PetrSvirak** [comment]
It should definitely be possible to add an email of a user who is not registered member yet – simply send a nice invitation if the email is not registered and another if there is already a user associated with the email. Also, you don't need CAPTCHA for authenticated user – it will only bother them.  

Anyway, CAPTCHA should always be displayed only after certain number of "trials" or "iterations" – lets say that, user can share <anything> with 20 users per day, unsuccessfully try to log-in 5 times (successful log-in resets the counter) and registration, well, it should be connected with certain IP/location, …, however, it is not easy to implement properly, so the CAPTCHA can be there all the time.

**Comment by Pebin** [comment]
changed url so it contains now link to user email instead of guid + add hash (reverted original idea of adding confirmation tokens into db because we are too close to launch event and there isn't enough time for testing)

what's missing (little todo for myself):
- add check whether requested permission wasn't already add
- don't allow user to accept the budget access before login and check whether correct user is logged in
- fix and add comments
+ something I definitely forgot

**Comment by PetrSvirak** [comment]
The decision about confirmation tokens is correct. Check my comments to the last commit. Otherwise it looks quite good now :wink:

**Comment by PetrSvirak** [comment]
As you could have seen, not following my advise on CAPTCHA resulted in criticism from my colleagues. This is one of the worst repaired issues of yours – so it is not that bad – but be careful about this in your future carriers. What I wanted to stress out is that some details are important. To decide what details are important, there is UX department (or person) – your bad luck was you had none, but the other two teams had one each.
